name: Deploy repository to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare public folder
        run: |
          rm -rf public
          mkdir public
          rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' ./ public/

      - name: Generate file-index.json
        run: |
          python3 - <<'PY'
          import subprocess, json
          files = subprocess.check_output(['git','ls-files']).decode().splitlines()
          repo = "TiagoProw/lerempixels-codebase"
          branch = "main"
          out = [{"path": f, "raw_url": f"https://raw.githubusercontent.com/{repo}/{branch}/{f}"} for f in files]
          with open('public/file-index.json','w',encoding='utf-
