name: Deploy repository to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare public folder
        run: |
          rm -rf public
          mkdir public
          # Ignora pastas e arquivos desnecessários automaticamente
          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='dist' \
            --exclude='build' \
            --exclude='.venv' \
            ./ public/

      - name: Generate file-index.json
        run: |
          echo "[" > public/file-index.json
          first=true
          for f in $(git ls-files); do
            [[ "$first" = true ]] && first=false || echo "," >> public/file-index.json
            url="https://raw.githubusercontent.com/TiagoProw/lerempixels-codebase/main/$f"
            echo "  {\"path\": \"$f\", \"raw_url\": \"$url\"}" >> public/file-index.json
          done
          echo "]" >> public/file-index.json

      - name: Upload and deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_path: ./public
